### ISSUE TITLE
Tem erro de digitação!

### ISSUE THREAD

**Issue by deafjava** [noahcascaes/Noah-Quiz#1]
https://github.com/noahcascaes/Noah-Quiz/blob/c2dbc25e36c10044b879877ce5361a9d78764415/4Pergunta.html#L21

Faltou "n" na palavra "Encotre"

**Comment by noahcascaes** [comment]
Ok, a equipe de programação vai resolver isso (talvez tenha só uma pessoa nesta equipe, que sou eu.)

**Comment by noahcascaes** [comment]
Seu erro foi resolvido pela equipe, entre em contato para saber mais:

***@***.***
Obrigado.

Em seg., 20 de mai. de 2024 às 15:40, Caio Cascaes ***@***.***>
escreveu:
